---
# tasks file for sample-mysql
- name: create partition
  parted:
    device: /dev/sdb
    number: 1
    state: present
    part_end: 800MiB

- name: create volume group
  lvg:
    vg: vg_database
    pvs: /dev/sdb1

- name: create lvol
  lvol:
    vg: vg_database
    lv: lv_mysql 
    size: 512m

- name: create filesystem
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql

- name: mount filesytem 
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: mounted

- name: install mysql-community-server
  yum:
          state: present
          name: mysql-server

- name: configure firewall
  firewalld:
    port: 3306/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: configure mysql service
  service:
          name: mysqld
          state: started
          enabled: yes

- name: copy config template
  template:
          src: my.cnf.j2
          dest: /etc/my.cnf
  notify: restart mysql






